name: AbbyBar
options:
  bundleIdPrefix: com.abby
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: 0.9.0

targets:
  AbbyBar:
    type: application
    platform: macOS
    sources:
      - AbbyBar
    dependencies:
      - package: WhisperKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abby.menubar
        PRODUCT_NAME: AbbyBar
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: AbbyBar/Info.plist
        CODE_SIGN_ENTITLEMENTS: AbbyBar/AbbyBar.entitlements
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        SWIFT_VERSION: 5.9
    info:
      path: AbbyBar/Info.plist
      properties:
        CFBundleName: AbbyBar
        CFBundleDisplayName: AbbyBar
        CFBundleIdentifier: com.abby.menubar
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: AbbyBar
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSMicrophoneUsageDescription: AbbyBar needs microphone access to transcribe your voice commands.
        NSHighResolutionCapable: true
    entitlements:
      path: AbbyBar/AbbyBar.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
